---
name: create a comment in jira when a pull request is opened or closed.

on:
  pull_request:
    types: [opened, closed]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Comment in jira
    steps:
      - uses: actions/checkout@v2

      ## checkout a second repository - we need this one to be able to notify JIRA
      ## a direct call to the action would require the action to be in a public repo
      - uses: actions/checkout@v2
        with:
          repository: levigo/Pull-Request-to-Jira-notifier
          ref: refs/tags/1.4.5
          path: notifier
          token: ${{ secrets.REPO_PTA }} # `REPO_PTA` contains a PersonalAccessToken to clone a private repo

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
      - name: fire an http request against jira
        id: jira_comment
        uses: ./notifier
        with:
          username: ${{ secrets.JIRA_USER }}
          password: ${{ secrets.JIRA_PASSWORD }}
          branchName: ${{ steps.extract_branch.outputs.branch }}
...